// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char GPRS_APN[]      = "mobile.bm";  // Put your sim infos here. Optional most of the time
const char PINNUMBER[]     = "1234";  // Also, those should be publicly available on your provider's website


CloudAngle boatHeading;
CloudLocation boatLocation;
CloudPower powerConsumption;
CloudTemperature cpuTemp;
CloudVelocity boatSpeed;

void initProperties(){

  ArduinoCloud.addProperty(boatHeading, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boatLocation, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(powerConsumption, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cpuTemp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boatSpeed, READ, ON_CHANGE, NULL);
}


NBConnectionHandler ArduinoIoTPreferredConnection(PINNUMBER, GPRS_APN);